---
- hosts: localhost
  tasks:
  - name: "Removing roles dir in case it exists"
    file:
      path: roles
      state: absent

  - name: "Cloning from git using galaxy"
    local_action: command ansible-galaxy install -f -r requirements.yml -p roles
